name: Create Directory Structure

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  create_structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Run make.py
        run: python make.py  # Run your script to create the directory structure

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Create directory structure" || echo "No changes to commit"
          git push
